// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { defineConfig } from '@prisma/config'
import { PrismaPg } from '@prisma/adapter-pg'
import * as dotenv from 'dotenv'
dotenv.config()

export default defineConfig({
  adapter: () => new PrismaPg({ connectionString: process.env.DATABASE_URL }),
  datasource: {
    url: process.env.DATABASE_URL
  }
})